name: hotel_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  google_nav_bar: ^5.0.6
  cloud_firestore: ^4.14.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.1
  curved_navigation_bar: ^1.0.3
  flutter_timezone: ^1.0.8
  timezone: ^0.9.2
  crypto: ^3.0.3
  google_maps_flutter: ^2.5.1
  provider: ^6.1.1
  font_awesome_flutter: ^10.6.0
  photo_view: ^0.14.0
  url_launcher: ^6.2.2
  pin_code_fields: ^8.0.1
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  grouped_list: ^5.1.2
  table_calendar: ^3.0.9
  qr_flutter: ^4.1.0
  equatable: ^2.0.5
  connectivity_plus: ^5.0.2
  expandable: ^5.0.1
  fluttertoast: ^8.2.4
  scroll_to_hide: ^2.1.0
  uuid: ^4.2.2
  screenshot: ^2.1.0
  path_provider: ^2.1.1
  image: ^4.1.3
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  dialog_flowtter: ^0.2.0-nullsafety.0
  http: ^1.1.2
  googleapis: ^12.0.0
  pub_updater: ^0.4.0
  xml: ^6.5.0
  google_fonts: ^6.1.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  carousel_slider: ^4.2.1
  group_list_view:
  badges: ^3.1.2

dev_dependencies:
  meta: ^1.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/final_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - lib/images/
    - lib/images/google.png
    - lib/images/logo.png
    - lib/images/user_management.png
    - lib/images/content_management.png
    - lib/images/booking_oversight.png
    - lib/images/review_moderation.png
    - lib/images/analytics_reporting.png
    - lib/images/system_settings.png
    - lib/assets/
    - lib/assets/hotel/
    - lib/images/default_profile_pic.jpg
    - lib/assets/pompeo/pompeo_1.jpg
    - lib/assets/pompeo/1.jpg
    - lib/assets/pompeo/pompeo_room_suites.png
    - lib/assets/pompeo/introPic/6.jpg
    - lib/assets/pompeo/introPic/7.jpg
    - lib/assets/pompeo/master_suite_img/master_suite_img.png
    - lib/assets/pompeo/master_suite_img/1.jpg
    - lib/assets/pompeo/master_suite_img/2.jpg
    - lib/assets/pompeo/master_suite_img/3.jpg
    - lib/assets/pompeo/master_suite_img/4.jpg
    - lib/assets/pompeo/master_suite_img/5.jpg
    - lib/assets/pompeo/master_suite_img/6.jpg
    - lib/assets/pompeo/master_suite_img/7.jpg
    - lib/assets/pompeo/master_suite_img/8.jpg
    - lib/assets/pompeo/master_suite_img/9.jpg
    - lib/assets/pompeo/master_suite_img/10.jpg
    - lib/assets/pompeo/junior_suite_img/junior_site_img.png
    - lib/assets/pompeo/junior_suite_img/1.jpg
    - lib/assets/pompeo/junior_suite_img/2.jpg
    - lib/assets/pompeo/junior_suite_img/3.jpg
    - lib/assets/pompeo/junior_suite_img/4.jpg
    - lib/assets/pompeo/junior_suite_img/5.jpg
    - lib/assets/pompeo/junior_suite_img/6.jpg
    - lib/assets/pompeo/junior_suite_img/7.jpg
    - lib/assets/pompeo/junior_suite_img/8.jpg
    - lib/assets/pompeo/junior_suite_img/9.jpg
    - lib/assets/pompeo/quad_room_img/quad_room_img.png
    - lib/assets/pompeo/quad_room_img/1.jpg
    - lib/assets/pompeo/quad_room_img/2.jpg
    - lib/assets/pompeo/quad_room_img/3.jpg
    - lib/assets/pompeo/quad_room_img/4.jpg
    - lib/assets/pompeo/quad_room_img/5.jpg
    - lib/assets/pompeo/quad_room_img/6.jpg
    - lib/assets/pompeo/quad_room_img/7.jpg
    - lib/assets/pompeo/quad_room_img/8.jpg
    - lib/assets/pompeo/quad_room_img/9.jpg
    - lib/assets/pompeo/quad_room_img/10.jpg
    - lib/presentation/home_screen_page/hotel_images/hotel_default_img.jpg
    - lib/assets/pompeo/pompeo_1.jpg
    - lib/assets/j_and_b/intro_pic/
    - lib/assets/j_and_b/standard_double_room_fan/
    - lib/assets/j_and_b/standard_family_room/
    - lib/assets/j_and_b/standard_double_room/
    - lib/assets/j_and_b/montage/
    - lib/assets/tourist_spot/casa_jose/
    - lib/assets/tourist_spot/casa_jose/montage/
    - lib/assets/tourist_spot/maniknik_falls/montage/
    - lib/assets/tourist_spot/maniknik_falls/
    - lib/assets/tourist_spot/sunchine_beach/montage/
    - lib/assets/tourist_spot/mataas_na_bato/
    - lib/assets/tourist_spot/mataas_na_bato/montage/
    - lib/assets/tourist_spot/gastadores_mountain_resort/montage/
    - lib/assets/tourist_spot/gastadores_mountain_resort/
    - lib/assets/tourist_spot/maguibuay_falls/montage/
    - assets/dialog_flow_auth.json
    - lib/assets/pompeo/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/UrbanistRomanBold.ttf
          weight: 700
        - asset: assets/fonts/UrbanistRomanBlack.ttf
          weight: 900
        - asset: assets/fonts/UrbanistSemiBold.ttf
          weight: 600
        - asset: assets/fonts/UrbanistRegular.ttf
          weight: 400
        - asset: assets/fonts/UrbanistRomanMedium.ttf
          weight: 500
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansProSemiBold.ttf
          weight: 600